### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by kibibites** [i-spin/lambda-bot-js#1]
and also plugin related stuff

**Comment by emyfops** [comment]
Just
fetch('https://api.github.com/orgs/lambda-client/repos')
🤓

**Comment by kibibites** [comment]
TODOs:
- Make a file that stores all the plugins in a json, similar to the capes file
- Would be optimal to save the releases so the user can choose
- Community submitted plugins through bot

**Comment by kibibites** [comment]
@Avanatiker seems right?

**Comment by emyfops** [comment]
Don't use json
Never
Use an actual databaae
Like redis

**Comment by emyfops** [comment]
#3
